package com.portalnetwork.checker

/**
 * Ported from PortalHackChecker.exe (PC version).
 * Every term here is a *weak* naming heuristic, never proof on its own -
 * matches should be treated as leads for review, same as the original tool.
 */
object ClientSignatures {

    // Strong identifiers: known cheat/utility client names or feature terms.
    val STRONG_NAME_TERMS: Map<String, String> = mapOf(
        "doomsday" to "Doomsday client identifier",
        "fps booster" to "FPS Booster identifier",
        "fpsbooster" to "FPS Booster identifier",
        "vape client" to "Vape client identifier",
        "vape" to "Vape identifier",
        "echo client" to "Echo client identifier",
        "echo" to "Echo identifier",
        "prestige client" to "Prestige client identifier",
        "prestige" to "Prestige identifier",
        "liquidbounce" to "LiquidBounce identifier",
        "aristois" to "Aristois identifier",
        "impact client" to "Impact client identifier",
        "impact" to "Impact identifier",
        "wurst" to "Wurst identifier",
        "meteor client" to "Meteor client identifier",
        "meteor" to "Meteor identifier",
        "bleachhack" to "BleachHack identifier",
        "thunderhack" to "ThunderHack identifier",
        "inertia" to "Inertia identifier",
        "wolfram" to "Wolfram identifier",
        "sigma" to "Sigma identifier",
        "future client" to "Future client identifier",
        "rusherhack" to "RusherHack identifier",
        "kami blue" to "KAMI Blue identifier",
        "konas" to "Konas identifier",
        "rise client" to "Rise client identifier",
        "tenacity" to "Tenacity identifier",
        "exhibition" to "Exhibition identifier",
        "raven" to "Raven identifier",
        "novoline" to "Novoline identifier",
        "augustus" to "Augustus identifier",
        "drip client" to "Drip client identifier",
        "moon client" to "Moon client identifier",
        "entropy" to "Entropy identifier",
        "skeet" to "Skeet identifier",
        "whiteout" to "Whiteout identifier",
        "fdp client" to "FDP client identifier",
        "myau" to "Myau identifier",
        "catlean" to "CatLean identifier",
        "nurik" to "Nurik client identifier",
        "moon lite" to "Moon Lite identifier",
        "celestial" to "Celestial client identifier",
        "astolfo" to "Astolfo client identifier",
        "flux client" to "Flux client identifier",
        "jello client" to "Jello client identifier",
        "salhack" to "Salhack identifier",
        "phobos" to "Phobos client identifier",
        "nekoclient" to "NekoClient identifier",
        "hero client" to "Hero client identifier",
        "swift client" to "Swift client identifier",
        "matrix client" to "Matrix client identifier",
        "slinky" to "Slinky client identifier",
        "weepcraft" to "Weepcraft identifier",
        "horion" to "Horion identifier",
        "zenith client" to "Zenith client identifier",
        "expensive client" to "Expensive client identifier",
        "nightx" to "NightX identifier",
        "toxin" to "Toxin client identifier",
        "obsidian client" to "Obsidian client identifier",
        "cracked client" to "Cracked client identifier",
        "leaked client" to "Leaked client identifier",
        "paid client" to "Paid client identifier",
        "private client" to "Private client identifier",
        "vape v4" to "Vape V4 identifier",
        "vape lite" to "Vape Lite identifier",
        "vape gui" to "Vape GUI identifier",
        "echo prestige" to "Echo Prestige identifier",

        // Feature / behavior terms
        "freecam" to "free-camera identifier",
        "free cam" to "free-camera identifier",
        "no fall" to "no-fall identifier",
        "nofall" to "no-fall identifier",
        "antiknockback" to "anti-knockback identifier",
        "anti knockback" to "anti-knockback identifier",
        "autoclicker" to "auto-clicker identifier",
        "auto clicker" to "auto-clicker identifier",
        "triggerbot" to "trigger-bot identifier",
        "trigger bot" to "trigger-bot identifier",
        "scaffold" to "scaffold identifier",
        "inventory move" to "inventory-move identifier",
        "blink" to "blink identifier",
        "reach hack" to "reach-hack identifier",
        "speed hack" to "speed-hack identifier",
        "fly hack" to "fly-hack identifier",
        "esp" to "ESP identifier",
        "chest esp" to "chest-ESP identifier",
        "nametags" to "nametags identifier",
        "hitbox" to "hitbox identifier",
        "critical" to "critical-hits identifier",
        "critical hits" to "critical-hits identifier",
        "spammer" to "chat-spammer identifier",
        "exploit" to "exploit identifier",
        "backdoor" to "backdoor identifier",
        "payload" to "payload identifier",
        "obfuscator" to "obfuscator identifier",
        "obfuscated client" to "obfuscated-client identifier",
        "ghost client" to "ghost-client identifier",
        "ghostclient" to "Ghost Client identifier",
        "blatant" to "blatant-client identifier",
        "cheat" to "cheat identifier",
        "hack" to "hack identifier",
        "killaura" to "kill-aura identifier",
        "kill aura" to "kill-aura identifier",
        "velocity" to "velocity identifier",
        "reach" to "reach identifier",
        "autoclick" to "auto-clicker identifier",
        "aimbot" to "aimbot identifier",
        "xray" to "X-ray identifier",
        "wallhack" to "wallhack identifier",
        "injector" to "injector identifier",
        "dll injector" to "DLL injector identifier",
        "client mod" to "client-mod identifier",
        "bypass" to "bypass identifier",
        "anticheat bypass" to "Anticheat bypass identifier",
        "watchdog bypass" to "Watchdog bypass identifier",
        "intave bypass" to "Intave bypass identifier",
        "vulcan bypass" to "Vulcan bypass identifier",
        "grim bypass" to "Grim bypass identifier",
        "polar bypass" to "Polar bypass identifier",
        "verus bypass" to "Verus bypass identifier",
        "nocheatplus bypass" to "NCP bypass identifier",
        "legit aura" to "legit-aura identifier",
        "silent aim" to "silent-aim identifier",
        "silentaim" to "silent-aim identifier",
        "autoblock" to "auto-block identifier",
        "autototem" to "auto-totem identifier",
        "auto32k" to "auto-32k identifier",
        "autopot" to "auto-pot identifier",
        "crystal aura" to "crystal-aura identifier",
        "crystalaura" to "crystal-aura identifier",
        "anchor aura" to "anchor-aura identifier",
        "burrow" to "burrow identifier",
        "nuker" to "nuker identifier",
        "longjump" to "longjump identifier",
        "bhop" to "bhop identifier",
        "noslowdown" to "no-slowdown identifier",
        "noslow" to "no-slow identifier",
        "fastuse" to "fast-use identifier",
        "fastplace" to "fast-place identifier",
        "fastbreak" to "fast-break identifier",
        "elytraboost" to "elytra-boost identifier",
        "boatfly" to "boatfly identifier",
        "packet fly" to "packet-fly identifier",
        "chams" to "chams identifier",
        "tracers" to "tracers identifier",
        "radar" to "radar identifier",
        "mob esp" to "mob-esp identifier",
        "player esp" to "player-esp identifier",
        "storage esp" to "storage-esp identifier",
        "item esp" to "item-esp identifier",
        "hacked client" to "hacked-client identifier",
        "cheat client" to "cheat-client identifier",
        "hvh client" to "HvH-client identifier",
        "crystalpvp" to "crystal-pvp identifier",
        "anarchy client" to "anarchy-client identifier"
    )

    // Ambiguous / weaker terms - flagged but explicitly low confidence.
    val AMBIGUOUS_NAME_TERMS: Set<String> = setOf(
        "drip", "moon", "rise", "client", "future", "watchdog"
    )

    // Mod-loader metadata files that indicate an installed mod/client jar.
    val MOD_METADATA_FILES: Set<String> = setOf(
        "mcmod.info",
        "quilt.mod.json",
        "fabric.mod.json",
        "neoforge.mods.toml",
        "mods.toml"
    )

    // Directories to skip while walking (system/noise locations).
    val SKIP_DIRS: Set<String> = setOf(
        "\\windows\\system32\\"
    )

    val REPORT_FILE_NAME = "portal_network_ss_baseline.json"
    val AI_CACHE_FILE = ".portal_network_ss"
}
